SCR_PlaceableEntitiesRegistry {
 m_Prefabs {
  "{A21AABD4235A65F5}Prefabs/Groups/CIV/Infantry/COA_CIV_RifleSquad_p.et"
  "{91AC884B31EDEE23}PrefabsMissionMaking/SpawnPoints/SpawnPoints/CIVILIAN_Spawn.et"
  "{E05C482DC753626A}PrefabsMissionMaking/SpawnPoints/SpawnPoints/Vehicles/CIV_MSP.et"
 }
}