SCR_PlaceableEntitiesRegistry {
 m_Prefabs {
  "{A21AABD4235A65F5}Prefabs/Groups/CIV/Infantry/CRF_CIV_RifleSquad_p.et"
  "{91AC884B31EDEE23}PrefabsMissionMaking/Systems/SpawnPoints/CIVILIAN_Spawn.et"
  "{E05C482DC753626A}PrefabsMissionMaking/Systems/SpawnPoints/Vehicles/CIV_MSP.et"
 }
}