SCR_EditorModePrefab {
 m_Mode STRATEGY
 m_Prefab "{6A6612AB7E3CA001}Prefabs/!Systems/Editor/Modes/COA_EditorModeTactical.et"
 m_ModeUIInfo SCR_EditorModeUIInfo "{6A6612AB7E3CA051}" {
  Name "Tactical Camera"
  Description "Overhead view of friendly units near you. Right-click a squad to give it orders."
  Icon "{AC7E384FF9D8016A}Common/Textures/placeholder_BCR.edds"
  m_ModeColor 0.5841 0.0369 0.0369 1
  m_iOrder 10
 }
}
